### PR TITLE
Add support for generating multiple files with OpenAPI Generator

### PR DESCRIPTION
**Pull request by christianhelle**
#### PR Classification
This pull request introduces a new feature that allows the generation of multiple files in the OpenApi C# generator.

#### PR Summary
The pull request adds a `GenerateMultipleFiles` option to the OpenApi C# generator, which can either copy source files to a destination directory and delete the source directory, or merge the source files, sanitize the merged file, and prefix it with an autogenerated code header.
- `OpenApiCSharpGeneratorCommand.cs` and `OpenApiCSharpCodeGenerator.cs` have been updated to handle the new `GenerateMultipleFiles` option.
- A new method `CopyFilesAndDeleteSource` has been added to `CSharpFileMerger.cs` to support the new feature.
- The `GenerateMultipleFiles` property has been added to `DefaultOpenApiGeneratorOptions.cs`, `IOpenApiGeneratorOptions.cs`, `OpenApiGeneratorOptions.cs`, and `OpenApiGeneratorOptionsPage.cs`.
- The `GenerateMultipleFiles` property value is now included in `OpenApiGeneratorOptions.cs`.

#### Screenshot
image

image

### CODE REVIEW

**Comment by christianhelle** [comment]
@kipusoep Is something like this interesting for you (see PR description)? I had someone request this to me at some point but I never got around to building it. I have a cold and have been sitting on the couch coding all day so I thought I could clean up the old backlog on my open-source projects

**Comment by kipusoep** [comment]
> @kipusoep Is something like this interesting for you (see PR description)? I had someone request this to me at some point but I never got around to building it. I have a cold and have been sitting on the couch coding all day so I thought I could clean up the old backlog on my open-source projects

I'm not sure what the context is? Interesting for what exactly? :-)

**Comment by kipusoep** [comment]
Sounds good, but I'm still not sure what it's got to do with me specifically 😅

**Comment by christianhelle** [comment]
> Sounds good, but I'm still not sure what it's got to do with me specifically 😅

LOL, I was pretty sure that you requested the feature but it seems I remembered wrong 😑

**Pull request merged**
