### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Jaxelr**
Fix minor typo

### CODE REVIEW

**Comment by Jaxelr** [comment]
Also, saw the word customising written a few times, i am under the impression that customizing is the correct spelling.

**Comment by christianhelle** [comment]
Well spotted sir!

**Comment by christianhelle** [comment]
> Also, saw the word customising written a few times, i am under the impression that customizing is the correct spelling.

Man you have a good eye! This is on purpose and I would like to keep spelling **_customising_** as I tend to default to **en-GB** as my display language and auto-correct features keep suggesting the British English spelling. As far as I know, its only spelled with a "z" in North America

**Comment by Jaxelr** [comment]
Good, i learned something new today. Thanks 😄

**Pull request merged**
